Remove incremental feature
Its implementation in GNU tar is broken and slow.

diff --git a/ssh-gpg-backup b/ssh-gpg-backup
--- a/ssh-gpg-backup
+++ b/ssh-gpg-backup
@@ -12,8 +12,8 @@ set -o errexit
 function depends
 for cmd in "$@"; do
     if ! which "$cmd" >/dev/null; then
-	echo "Command '$cmd' is required.  Please, install it."
-	exit 1
+	      echo "Command '$cmd' is required.  Please, install it."
+	      exit 1
     fi
 done
 
@@ -22,23 +22,19 @@ function usage
     echo "\
 Usage: $0 [USER@]HOST [REMOTE-ROOT-DIR]
 
-Incrementally backup entire directory tree underneath HOST's
-REMOTE-ROOT-DIR using USER's SSH access.
+Backup entire directory tree underneath HOST's REMOTE-ROOT-DIR using
+USER's SSH access.
 
 USER defaults to the current user.  REMOTE-ROOT-DIR defaults to /, but
 one might be interested in using just /home/USER, for example.
 
-The (Tar-archived) backup and its SNAR snapshot file are Gzip-compressed
-and GPG-encrypted inside the local directory HOST/, relative to the
-current working directory.
+The (Tar-archived) backup file is Gzip-compressed and GPG-encrypted
+inside the local directory HOST/, relative to the current working
+directory.
 
 GNU Tar is used on the remote host to archive the backup before
 sending it over the network, and therefore must be available in its
 PATH.  Compression and encryption are performed on the local side.
-
-Naturally, in case a previously made incremental backup (alongside its
-'snapshot.snar.gz.gpg' file) is present in the aforementioned
-destination directory, a higher level backup will be made.
 
 This program asks for the GPG passphrase before starting its actual
 work." 1>&2
@@ -47,17 +43,17 @@ work." 1>&2
 function ssh_bash
 {
     ssh "$user_host" \
-	bash --noprofile --norc
+	      bash --noprofile --norc
 }
 
 function ssh_bash_gz_gpg
 {
     ssh_bash |
-	gzip |
-	gpg --batch \
-	    --passphrase-file=<(cat <<<"$passphrase") \
-	    --symmetric \
-	    --quiet
+	      gzip |
+	      gpg --batch \
+	          --passphrase-file=<(cat <<<"$passphrase") \
+	          --symmetric \
+	          --quiet
 }
 
 depends ssh gzip gunzip gpg
@@ -78,18 +74,6 @@ host=${user_host#*@}
 remote_root_dir=${2:-/}
 backup_dir=$host
 mkdir --parents "$backup_dir"
-local_snar_file=$backup_dir/snapshot.snar.gz.gpg
-remote_snar_file=$(ssh_bash <<<'mktemp --suffix=.snar')
-
-if [[ -f $local_snar_file ]]; then
-    gpg --batch \
-	--passphrase-file=<(cat <<<"$passphrase") \
-	--decrypt \
-	--quiet \
-	"$local_snar_file" |
-	gunzip |
-	ssh "$user_host" "cat > '$remote_snar_file'"
-fi
 
 ssh_bash_gz_gpg <<EOF >"$backup_dir/$(date -Iseconds)".tar.gz.gpg
 set -e
@@ -125,8 +109,5 @@ fi
   --exclude=/var/run \
   --exclude=/var/tmp \
   --one-file-system \
-  --listed-incremental='$remote_snar_file' \
   '${remote_root_dir}'
 EOF
-
-ssh_bash_gz_gpg <<<"cat '$remote_snar_file'" >"$local_snar_file"
diff --git a/ssh-gpg-backup-restore b/ssh-gpg-backup-restore
--- a/ssh-gpg-backup-restore
+++ b/ssh-gpg-backup-restore
@@ -12,8 +12,8 @@ set -o errexit
 function depends
 for cmd in "$@"; do
     if ! which "$cmd" >/dev/null; then
-	echo "Command '$cmd' is required.  Please, install it."
-	exit 1
+	      echo "Command '$cmd' is required.  Please, install it."
+	      exit 1
     fi
 done
 
@@ -24,11 +24,11 @@ function usage
     echo "\
 Usage: $0 [USER@]HOST
 
-Restore incremental backup made by ssh-gpg-backup.
+Restore backup made by ssh-gpg-backup.
 
-The Gzip-compressed, GPG-encrypted (Tar-archived) backup and its SNAR
-snapshot file are expected inside the local directory HOST/, relative
-to the current working directory.
+The Gzip-compressed, GPG-encrypted (Tar-archived) backup file is
+expected inside the local directory HOST/, relative to the current
+working directory.
 
 GNU Tar is used on the remote host to extract the backup archive sent
 over the network, and therefore must be available in its PATH.
@@ -45,7 +45,7 @@ trap usage EXIT
 trap EXIT
 
 user_host=$1
-host=${user_host#@}
+host=${user_host#*@}
 
 read -r \
      -p 'GPG encryption.  Enter passphrase: ' \
@@ -54,15 +54,14 @@ echo
 
 for backup_file in "$host"/*.tar.gz.gpg; do
     gpg --batch \
-	--passphrase-file=<(cat <<<"$passphrase") \
-	--decrypt \
-	--quiet \
-	"$backup_file" |
-	gunzip |
-	ssh "$user_host" \
-	    tar \
-	    --verbose \
-	    --directory=/ \
-	    --extract \
-	    --incremental
+	      --passphrase-file=<(cat <<<"$passphrase") \
+	      --decrypt \
+	      --quiet \
+	      "$backup_file" |
+	      gunzip |
+	      ssh "$user_host" \
+	          tar \
+	          --verbose \
+	          --directory=/ \
+	          --extract
 done
